ac_max: 1
ac_min: -1
actor_lr: 0.001
actor_hidden_dim: 256
critic_lr: 0.001
critic_hidden_dim: 256
memory: 1000000
episodes: 8000
gamma: 0.995
batch_size: 256
target_update_freq: 5
actor_update_freq: 2
td3_exploration_start: 0.30
td3_exploration_min: 0.01
td3_exploration_decay: 2500
td3_noise_clip: 0.5
replay_buffer: 100