ac_max: 2
ac_min: -2
actor_lr: 0.0003
actor_hidden_dim: 256
critic_lr: 0.0003
critic_hidden_dim: 256
memory: 1000000
episodes: 3000
gamma: 0.99
batch_size: 512
target_update_freq: 10
actor_update_freq: 5
td3_exploration_start: 0.2
td3_exploration_min: 0.01
td3_exploration_decay: 0.995
replay_buffer: 20
reward_scale: 10
max_grad_norm: 1.0
log_prob_clip: 5.0
reward_clip: 5.0