ac_max: 0.4
ac_min: -0.4
actor_lr: 0.0005
actor_hidden_dim: 512
critic_lr: 0.0005
critic_hidden_dim: 512
memory: 1000000
episodes: 15000
gamma: 0.995
batch_size: 512
target_update_freq: 1
actor_update_freq: 2
td3_exploration_start: 0.25
td3_exploration_min: 0.01
td3_exploration_decay: 2000
td3_noise_clip: 0.5
replay_buffer: 20