ac_max: 1
ac_min: -1
actor_lr: 0.005
actor_hidden_dim: 256
critic_lr: 0.005
critic_hidden_dim: 256
memory: 1000000
episodes: 2000
gamma: 0.995
batch_size: 512
target_update_freq: 5
actor_update_freq: 2
replay_buffer: 20
log_prob_clip: 5.0