ac_max: 1
ac_min: -1
actor_lr: 0.0007
actor_hidden_dim: 256
critic_lr: 0.005
critic_hidden_dim: 256
memory: 1000000
episodes: 1000
gamma: 0.99
batch_size: 512
target_update_freq: 10
actor_update_freq: 5
td3_exploration_start: 0.25
td3_exploration_min: 0.00001
td3_exploration_decay: 0.95
td3_noise_clip: 0.5
replay_buffer: 20
reward_scale: 10