ac_max: 1
ac_min: -1
actor_lr: 0.0001
actor_hidden_dim: 256
critic_lr: 0.005
critic_hidden_dim: 256
memory: 1000000
episodes: 500
gamma: 0.99
batch_size: 512
target_update_freq: 5
actor_update_freq: 10
td3_exploration_start: 0.25
td3_exploration_min: 0.00001
td3_exploration_decay: 0.97
replay_buffer: 20
reward_scale: 10
max_grad_norm: 2.5
log_prob_clip: 5.0
reward_clip: 20.0